on: [push]

jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
       - name: Discord Commits
         uses: Sniddl/discord-commits@v1.5
         with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: 'avatar-with-link'
          include-extras: true
